repos:
-   repo: local
    hooks:
      - id: format
        name: format
        entry: ruff format
        language: system
        types: [python]
        files: \.py$
      - id: lint
        name: lint
        entry: ruff check
        language: system
        types: [python]
        files: \.py$