[project]
name = "cv-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "opencv-python>=4.11.0.86",
    "pre-commit>=4.2.0",
    "ruff>=0.11.11",
    "ultralytics>=8.3.143",
]
